insert into post_seeder (title, body) values ('Macbeth (a.k.a. Tragedy of Macbeth, The)', 'Illeg ab w compl NEC-inc');
insert into post_seeder (title, body) values ('Cat People', 'Acq total absnc pancreas');
insert into post_seeder (title, body) values ('Young Bess', 'Ac pyelonephr w med necr');
insert into post_seeder (title, body) values ('Sound of Noise', 'Chr stomach ulcer NOS');
insert into post_seeder (title, body) values ('Marvin Gaye: What''s Going On', 'Mach acc-occ power boat');
insert into post_seeder (title, body) values ('Late Great Planet Earth, The', 'Malig neo upper gum');
insert into post_seeder (title, body) values ('Hen, his wife', 'NB late anemia:isoimmun');
insert into post_seeder (title, body) values ('Oasis', 'TB of bladder-micro dx');
insert into post_seeder (title, body) values ('Case départ', 'Fracture five ribs-open');
insert into post_seeder (title, body) values ('Mondo Topless', 'Pathologic alcohol intox');